### ISSUE TITLE
configurable server / certificate

### ISSUE THREAD

**Issue by thestinger** [copperhead/Noise#1]

**Comment by legovini** [comment]
Will this be done before releasing Noise, or will you ship it configured to use the official servers, distributing a client that violates the terms of service of the OWS Signal servers?

**Comment by thestinger** [comment]
I've never seen or agreed to any terms of service for the OWS Signal server... where exactly are those?

**Comment by legovini** [comment]
Now I can't find a legalese ToS page, but moxie has been quite explicit about this several times, for example here:

https://github.com/LibreSignal/LibreSignal/issues/37#issuecomment-217211165
https://github.com/LibreSignal/LibreSignal/issues/37#issuecomment-217211165

These are the comments that killed LibreSignal. On the reasons why moxie doesn't want the official client to be distributed outside the Play store see this comment:

https://github.com/WhisperSystems/Signal-Android/issues/127#issuecomment-13335689

**Comment by thestinger** [comment]
I've gone as far as I need to go in terms of legality by removing the trademark and respecting the GPL3 license. I plan on going further by changing the icon and removing the hard-wired default server, but I don't consider it blocked on that. I'm not interested in trying to keep people happy, only not violating the law. Note that this app isn't going to be promoted or put in the main F-Droid repository or Google Play and use in CopperheadOS will be discouraged except as a last resort which is exactly what the documentation already does.

I haven't agreed to any terms of use. I wasn't presented with anything like that when I opened up the standard Signal app. I'm also not using their servers, our users are. I plan on making it possible for them to use other servers, but I don't *have* to do that. I only plan on doing that to be more diplomatic, not for legal reasons, and I don't care enough about being diplomatic to make it a priority.

**Comment by tuxayo** [comment]
> I'm also not using their servers, our users are. 

Users should be aware of that.

Using someone's servers against it's will is quite bad. And for a secure messaging solution there is something wrong with that even if it's end-to-end encrypted.

This is also a risk for availability, so users should know to not depend on Noise for any important stuff.

**Comment by thestinger** [comment]
The documentation recommends against using it before Signal has non-GCM support upstream. Not interested in whining about it, sorry.

**Comment by thestinger** [comment]
https://en.wikipedia.org/wiki/Signal-to-noise_ratio

Submit pull requests to projects, not complaints about changes being missing that the project states are planned. There's no point... it doesn't increase the priority. All of the complaints about Signal not supporting non-GCM similarly didn't accomplish anything, while at least someone submitting a clean set of patches allowed for this to exist and should end up landing in Signal itself soon enough.

**Comment by thestinger** [comment]
No longer planned, since the need for Noise is quickly going away.
