### ISSUE TITLE
Noise update status?

### ISSUE THREAD

**Issue by roadkillazpartybird** [copperhead/Noise#10]
Sorry if this isn't the right spot for this.

I noticed Play store has Signal 3.29.6 while Noise is still on 3.29.2. 

Is Noise still being updated regularly? Also when do you expect Signal will merge these changes? When that happens will Noise continue, or will using another repo to get Signal be required?

Thanks, love your work.

**Comment by thestinger** [comment]
It will be updated when I have time to update it. I have a whole OS to maintain without any help and I have a lot of work to do on that right now. Noise is a very low priority. I have an open PR at https://github.com/WhisperSystems/libsignal-service-java/pull/34 which is a prerequisite.
