### ISSUE TITLE
App just doesn't work

### ISSUE THREAD

**Issue by Rudd-O** [copperhead/Noise#6]
I installed it and it authorized my phone.  IT worked at the beginning.  Now it doesn't let me send any messages to existing conversations, all they are is undelivered.  Messages to new numbers show the button "allow noise to send sms" or something.   Going to "linked devices" in the settings just says "Network connection failed..." and [cancel] [try again].

Why is it not working anymore?

**Comment by ddast** [comment]
Go to settings, unregister and register again.  Then it should work again.  Your keys will not change that way.

There is some discussion on [Reddit](https://www.reddit.com/r/CopperheadOS/comments/5kauzg/copperhead_fdroid_repository/dboeh0i/) regarding this problem.  It seems to me that it happens more frquently to Noise users than to Signal users, but it does not apply to all people.

**Comment by Rudd-O** [comment]
There is no menu item to do that in the settings.

**Comment by ddast** [comment]
It's under Settings - Advanced - "Noise messages and calls".  You need to toggle it to off and then to on again.

**Comment by Rudd-O** [comment]
OK, that should be documented.  I would have never known that setting was what caused unregistering and registering.

**Comment by Rudd-O** [comment]
Your suggestion worked.  Thanks.

**Comment by thestinger** [comment]
This is a Signal issue, not a Noise one.
