### ISSUE TITLE
Noise in F-Droid for non-Copperhead users

### ISSUE THREAD

**Issue by herbsmn** [copperhead/Noise#7]
Please correct me if I am wrong, but is Noise only in Copperhead's version of F-Droid? Has any work been done to add it to the main F-Droid repo? If that isn't desireable, is there a Copperhead F-Droid repo that people can add in order to get it?

**Comment by thestinger** [comment]
I don't plan on putting in more effort into this than I am already. It's in the Copperhead F-Droid repository but that isn't intended to continue working elsewhere, and I don't want to encourage people to use it only for it to stop working later which means complaints about something predictable.

**Comment by jomo** [comment]
For the record, the Copperhead F-Droid repository [is this](https://copperhead.co/android/docs/usage_guide#signal) one:

https://fdroid.copperhead.co/repo?fingerprint=F0D4EB1193AD82FEB224BD1174B6FBD89A39D8ED988C9FFF2ADD0DCD1C4E271B

**Comment by herbsmn** [comment]
thanks @jomo but that repo doesn't seem to be working on my non-Copperhead phone.
