### ISSUE TITLE
Install error

### ISSUE THREAD

**Issue by gethob1** [copperhead/Noise#8]
When I try to install Noise from the https://fdroid.copperhead.co/repo?fingerprint=F0D4EB1193AD82FEB224BD1174B6FBD89A39D8ED988C9FFF2ADD0DCD1C4E271B repository it gives an error message "Install Error   Failed to install due to an unknown error" with an OK button.  Please help fix, thanks.

**Comment by thestinger** [comment]
It won't work if you have LibreSignal or Signal installed.
